"use client";

import { motion } from "framer-motion";
import { Terminal } from "lucide-react";

export default function About() {
  return (
    <section id="about" className="relative py-24 sm:py-32 px-6">
      <div className="max-w-3xl mx-auto">
        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.6 }}
        >
          <p className="text-sm font-[family-name:var(--font-mono)] text-cyan-400/70 mb-3 tracking-wide uppercase">
            About
          </p>
          <h2 className="text-3xl sm:text-4xl font-semibold tracking-tight mb-8">
            The operator behind the agents
          </h2>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-50px" }}
          transition={{ duration: 0.6, delay: 0.2, ease: [0.16, 1, 0.3, 1] }}
          className="rounded-2xl border border-white/[0.06] bg-white/[0.02] p-6 sm:p-8"
        >
          {/* Terminal header */}
          <div className="flex items-center gap-2 mb-6 pb-4 border-b border-white/[0.06]">
            <div className="flex gap-1.5">
              <span className="w-3 h-3 rounded-full bg-red-400/60" />
              <span className="w-3 h-3 rounded-full bg-yellow-400/60" />
              <span className="w-3 h-3 rounded-full bg-green-400/60" />
            </div>
            <div className="flex items-center gap-1.5 ml-3">
              <Terminal size={14} className="text-neutral-500" />
              <span className="text-xs text-neutral-500 font-[family-name:var(--font-mono)]">
                ~/about
              </span>
            </div>
          </div>

          <div className="space-y-4 text-neutral-400 leading-relaxed">
            <p>
              I&apos;m{" "}
              <span className="text-white font-medium">Prannay Reddy</span>, a
              software engineer who discovered that the most interesting code
              is the code you don&apos;t write yourself.
            </p>
            <p>
              My current obsession: orchestrating AI agents to build production
              systems autonomously. Not toy demos &mdash; real products, deployed
              to real users, handling real crises.
            </p>
            <p>
              During the 2026 Gulf Crisis, I used{" "}
              <span className="text-cyan-400/80">Perplexity Computer</span> to
              build and deploy a crisis resource hub in under an hour &mdash;
              complete with autonomous monitoring, auto-deployment, and live
              data feeds. That&apos;s when I realized: this is how software gets
              built now.
            </p>
            <p className="text-neutral-500 text-sm font-[family-name:var(--font-mono)]">
              This portfolio is itself an AI-built artifact. Every line of code
              was generated by an AI agent, pushed to GitHub, and deployed to
              Vercel — autonomously.
            </p>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
